version: '2'
services:
    mhasibuchurchusers-app:
        image: ghacupha/mhasibu-church-users:0.0.1-SNAPSHOT
        volumes:
            - ./logs/:/logs/
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            #- SPRING_DATASOURCE_URL=jdbc:postgresql://mhasibuchurchusers-postgresql:5432/mhasibuChurchUsers
            - SPRING_DATASOURCE_URL=${LOCAL_PG_SERVER}/${MCU_SYSTEM_PROD_DB}
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - MCU_SYSTEM_PROD_PORT=${MCU_SYSTEM_PROD_PORT}
            - MCU_SYSTEM_DEV_PORT=${MCU_SYSTEM_DEV_PORT}
            - LOCAL_PG_SERVER=${LOCAL_PG_SERVER}
            - MCU_SYSTEM_PROD_DB=${MCU_SYSTEM_PROD_DB}
            - MCU_SYSTEM_DEV_DB=${MCU_SYSTEM_DEV_DB}
            - PG_DATABASE_PROD_USER=${PG_DATABASE_PROD_USER}
            - PG_DATABASE_PROD_PASSWORD=${PG_DATABASE_PROD_PASSWORD}
            - PG_DATABASE_DEV_USER=${PG_DATABASE_DEV_USER}
            - PG_DATABASE_DEV_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
            -
    mhasibuchurchusers-postgresql:
        extends:
            file: postgresql.yml
            service: mhasibuchurchusers-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
